name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build and zip extensions
        run: |
          bunx wxt zip
          bunx wxt zip -b firefox

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .output/*-chrome.zip
            .output/*-firefox.zip
            .output/*-sources.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
